<?php

namespace AppBundle\Repository;

/**
 * BusinessCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessCardRepository extends \Doctrine\ORM\EntityRepository
{
}
